version: "3"
services:
  mongo:
    image: joseemgp/p2gps:db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.15"
          #memory: 200M
      restart_policy:
        condition: none
    ports:
      - "28017"
      - "27017"
    volumes:
      - "db-data:/data/db"
  order:
    image: joseemgp/p2gps:order
    depends_on:
      - "mongo"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          #memory: 500M
      restart_policy:
        condition: none
    ports:
      - "8080"
  web:
    image: joseemgp/p2gps:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
         # memory: 300M
      restart_policy:
        condition: none
    ports:
      - "8082"

volumes:
  db-data: